name: HAPI FHIR CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  IMAGE_NAME: docker.io/mikko1213/hapi-fhir-jpaserver
  JAVA_VERSION: 17
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Download repository source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      # 3. Cache Maven dependencies
      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build HAPI FHIR project
      - name: Build Project
        run: mvn clean install -DskipTests

      # 5. Run Unit Tests
      - name: Run Tests
        run: mvn test

      