name: Build Container Images

on:
  push:
    tags:
      - "image/v*"
    paths-ignore:
      - "charts/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "charts/**"
env:
  IMAGES: docker.io/hapiproject/hapi
  PLATFORMS: linux/amd64,linux/arm64/v8

