name: Simple CI/CD Demo

on:
  push:
    branches:
      - main

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Download Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Show Files
      - name: Show Files
        run: ls

      # Step 3: Print Message
      - name: Run Simple Command
        run: echo "CI/CD Pipeline is Working!"

      # Step 4: Show Current Date
      - name: Show Date
        run: date

      # Step 5: Finish
      - name: Complete
        run: echo "Pipeline Completed Successfully"